### ISSUE TITLE
Unittests against external services [investigation]

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#48]
B2ACCESS and B2HANDLE would be accessed only as external services,
and they will not - at least for the moment - dockerized in our set of images.

To mock their interaction in unittests we may take advantage of libraries
like [betamax](http://betamax.readthedocs.io/en/latest/) to record and replay their calls.

**Comment by mdantonio** [comment]
> To mock their interaction in unittests we may take advantage of libraries like betamax to record and replay their calls

I tried betamax and it works but I also tried [VCR.py](https://github.com/kevin1024/vcrpy).
Both of them are python portings of [VCR](https://github.com/vcr/vcr)

However after some basic test i preferred the second one:

- it is more convenient to be used because it provides a decorator (also callable without any parameters) instead a with , who requires to intendend the code (with all the PEP8 related annoyances)
- while betamax can be used only with requests.session, vcr.py can be used with a long list of libraries (requests, aiohttp, urllib3, tornado, urllib2, boto, boto3)
- both the project are well supported on github but vcr.py has more commits, more branches, more releases and more contributors (17 contributors with 1 main contributor on betamax, 54 contributors with a couple of main contributors)

**Comment by mdantonio** [comment]
Another option is [vcrpy-unittest](https://github.com/agriffis/vcrpy-unittest)

### Unittest Integration
_While it’s possible to use the context manager or decorator forms with unittest, there’s also a VCRTestCase provided separately by vcrpy-unittest._

But to be honest I don't see advantages

**Comment by mdantonio** [comment]
Simple setup to work with vcr:

`pip install vcr`

_____________


```
import vcr
import requests
[...]

    @vcr.use_cassette('test/cassettes/mytest.yaml')
    # cassette file will have the same name as the test function and will be
    # placed in the same directory as the file in which the test is defined
    # @vcr.use_cassette()
    def test_01_GET_status(self):
        requests.get('www.google.com')
        [...]
```

________________________

if `test/cassettes/mytest.yaml` is not found will be created with the first request. Otherwise can be pre-created

**Comment by mdantonio** [comment]
Could be useful to configure the library behavior, for example to handle recorded cassettes

https://vcrpy.readthedocs.io/en/latest/usage.html

Default is once (cassette is created if not found), but could be useful to configure none (cassette cannot be created at runtime, but only pre-created)

```
import vcr
my_vcr = vcr.VCR(
    cassette_library_dir='test/cassettes',
    record_mode='once',
)
[...]
    @my_vcr.use_cassette('status.yaml')
    def test_01_GET_status(self):
        """ Test that the flask server is running and reachable """

        response = requests.get('http://www.iana.org/domains/reserved')
        log.critical(response.status_code)
        [...]
```

**Comment by mdantonio** [comment]
I tested b2access authentication and found several problem. I put some fix and some workaround in the code, you can find them by searching for the label "TO FIX: FROM MATTIA"

By applying such workarounds i were able to complete a b2access authentication (more or less) but at now i'm unable to continue:

**b2access athentication via browser**
By opening /auth/ask on a browser I'm able to authenticate on Unity and obtain a b2access token. Then the endpoint gives an error:

```
DEBUG @rapydo.services.authentication.sqlalchemy Existing internal user: [db model: User] None ([<rapydo.models.sqlalchemy.Role object at 0x7fe0a9a63d68>])
INFO  @rapydo.services.authentication.sqlalchemy Created external user [db model: ExternalAccounts] None(None):None
ERROR @rapydo.decorators (psycopg2.IntegrityError) null value in column "username" violates not-null constraint
DETAIL:  Failing row contains (null, 5XgzTh0M5N84jfCqzTycgEFrmivN5CBbSMX4cUrqdAw, null, null, null, /C=DE/L=Juelich/O=FZJ/OU=JSC/CN=13148ea2-4d02-4d2f-b36b-0a646980..., null, null, 2, null, 13148ea2-4d02-4d2f-b36b-0a646980c779).
 [SQL: 'INSERT INTO external_accounts (token, token_expiration, email, certificate_cn, certificate_dn, proxyfile, description, user_id, irodsuser, unity) VALUES (%(token)s, %(token_expiration)s, %(email)s, %(certificate_cn)s, %(certificate_dn)s, %(proxyfile)s, %(description)s, %(user_id)s, %(irodsuser)s, %(unity)s)'] [parameters: {'token': '5XgzTh0M5N84jfCqzTycgEFrmivN5CBbSMX4cUrqdAw', 'token_expiration': None, 'email': None, 'certificate_cn': None, 'certificate_dn': "/C=DE/L=Juelich/O=FZJ/OU=JSC/CN=13148ea2-4d02-4d2f-b36b-0a646980c779/CN=Paolo D'Onorio De Meo", 'proxyfile': None, 'description': None, 'user_id': 2, 'irodsuser': None, 'unity': '13148ea2-4d02-4d2f-b36b-0a646980c779'}]
INFO  @rapydo.server GET http://localhost:8080/auth/authorize?code=FEu9DacvxNCa2LNfuOUgVV2vC9T4A0wSJzR_M5D6x30 {} <InternalResponse 1201 bytes [400 BAD REQUEST]>
```

**b2access athentication via command line**
I tried the same workflow by calling /auth/askauth. I'm able to authenticate on Unity and obtain, the callback uri (auth/authorize) is called with a code, then the endpoint is not able to exchange the code for a token

```
DEBUG @flask_oauthlib Prepare oauth2 remote args {'code': 'YY4SpGRnIKZLqh1xqndr8RcLwnwC4Xo93C-bgisVG8c', 'client_secret': '************', 'redirect_uri': None}
DEBUG @flask_oauthlib Request 'https://unity.eudat-aai.fz-juelich.de:8443/oauth2/token' with 'POST' method
CRITICAL @eudat.apis.oauth Failed to get authorized @B2access: Invalid response from b2access
```

'redirect_uri': in this case is None and in the previous case is http://localhost:8080/auth/authorize

I'm not able to understand why the uri is None and how to fix it

**b2access athentication via tests**

From tests i can call /auth/askauth and obtain the redirect URI from the Location header. But since the flask server is internal to the tests, the URI contains a wrong reference to the callback function (127.0.0.1:5000 instead of localhost:8080). This is not a real problem (also with a right URI we are unable to call b2access from tests, because there is no backend server able to respond to the callback) but it remains a different behaviour (and different behaviours during tests do not help to test something).

**mocked b2access athentication**

We want to mock the authentication using betamax / vcr but i fear that we simply cannot.

After obtained the redirect location from /askauth we can mock the Unity call
Unity responds with a code and if we mock this call we can only respond with an invalid code, because it is a fake code (if the call is completely mocked) or an expired code (if the call is replied via betamax/vcr)
Then we can call /authorize and pass the code
/authorize will contact b2access to exchange the code with a token but this operation will fail, because the code is invalid. So we have to mock also the /authorize call and return a fake token

The point is: after calling /askauth and obtained the redirect uri, what we can test if we have to mock everything?

At now the only things we are able to test are:

- /askauth responds with a 302 FOUND
- /askauth responds with a Location in the header
- the Location is a valid URL (or: Location is exactly the expected URL)
- /authorize gives an error if no code is given in input
- /authorize gives an error if an invalid code is given in input

Such tests are really not enough to ensure that this authentication works properly

**Comment by mdantonio** [comment]
I pushed all fixes and tests both in http-api (branch: oauth2) and http-api-base (on master).

**Comment by pdonorio** [comment]
Things to be tested if possible with this mechanism:

- [ ] b2handle external
- [ ] b2access external token, and also proxy regeneration
- [ ] b2safe external pid and checksum

**Comment by pdonorio** [comment]
Note to self: I created [a topic](https://forum.pythonistacafe.com/t/mocking-external-services-into-your-unittest/320) in a private forum for this.

**Comment by pdonorio** [comment]
Waiting for better instructions between RC and PRODUCTION

**Comment by pdonorio** [comment]
Not time/effort for the first stable release
