### ISSUE TITLE
Becoming compliant to the future Rapydo structure

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#60]
A few tips to be applied to become again compliant with the future rapydo system

**Comment by pdonorio** [comment]
We have a new branch for all modifications of the this milestone (0.3.2).

Since the modifications from this issue are breaking compatibility we should actually think of the next release as a major update (0.4).

I've tested the new branch rapydo-compliant on all DEBUG modes. 

Development and production yet to be tested, especially in a VM in production :)

**Comment by pdonorio** [comment]
To complete this part we must use [the new do python command](https://github.com/rapydo/do) correctly, also for travis tests.

**Comment by pdonorio** [comment]
This is going very good. 
The new [0.4.0 branch]() has [just passed all tests on travis](https://travis-ci.org/EUDAT-B2STAGE/http-api/builds/237542002) with the new rapydo controller package 👍 🎉 

Things to do now:

- [ ] fix a quick start documentation page at least
- [ ] search for possible `rapydo` requirements from eudat implementation
- [ ] test production mode
- [ ] remove the old do bash script

**Comment by pdonorio** [comment]
This repo should be a fork of `rapydo/core`.

To evaluate: possible solution to do so...

**Comment by mdantonio** [comment]
I done this:
```
git clone https://github.com/EUDAT-B2STAGE/http-api mergeeudat
cd mergeeudat
git checkout 0.4.0
git remote add upstream https://github.com/rapydo/core
git fetch upstream
git checkout -b testmerge
git merge upstream/master

-- fix all conflicts --

git commit -m "first rapydo merge"
git push origin testmerge

```

And the result is this:

https://github.com/EUDAT-B2STAGE/http-api/tree/testmerge

The histories are clearly merged

Then i pushed a modification on rapydo-core (commit 37341ea) and pulled again from EUDAT:

`git pull upstream master`

And i found no problem at all... the commit has been pulled and merged into EUDAT and is now available in the history

I suggest you to perform again these steps as soon as possible to become fully compliant. Do not trust the testmerge branch (it should be simply deleted) because i resolved the conflicts very quickly just to complete the test

**Comment by pdonorio** [comment]
Wow, cool! Than this should be tested today before the periodic eudat release

**Comment by pdonorio** [comment]
> I suggest you to perform again these steps as soon as possible to become fully compliant.

The new branch [0.4.1](https://github.com/EUDAT-B2STAGE/http-api/tree/0.4.1) is now able to do the `git pull upstream master` and has the merge history

**Comment by mdantonio** [comment]
> The new branch 0.4.1 is now able to do the git pull upstream master and has the merge history

Just a note for posterity: my instructions (in particular: `git merge upstream/master`) only works with older git versions (i used git 2.7.4). Recents git versions do not allow this merge due to "unrelated histories".
To force the merge you have to add the flag [--allow-unrelated-histories](https://git-scm.com/docs/git-merge#git-merge---allow-unrelated-histories)
