### ISSUE TITLE
EPOS use case

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#73]
Tracking the activity for this HTTP API prototype

**Comment by pdonorio** [comment]
We are now using the branch [airods](https://github.com/EUDAT-B2STAGE/http-api/tree/airods) while [mongo_gui](https://github.com/EUDAT-B2STAGE/http-api/tree/mongo_gui) is to be integrated with @mdantonio

**Comment by massimo1962** [comment]
Now the  API/Airods implements the search via bounding box and time window to retrieve the digital object (daily granularity; for  time being)  or metadata (dublin core) associated in EPOS catalogue.
In development environment all the things go well.
The issue encountered is due to the fact that the connection between HTTP-API and the Irods instance (B2SAFE production node) doesn't works; likely becouse there is a version problem. 
We have experienced a couple of issues: 1) the Python client of iRODS (PRC) have some connection - interaction problems; 2) the connection between API and Irods without GSI.

**Comment by pdonorio** [comment]
This pilot was completed and presented.
We can close now here and let the work go on in the next months.
