### ISSUE TITLE
rapydo internal modules not found

### ISSUE THREAD

**Issue by Vathasav** [EUDAT-B2STAGE/http-api#85]
I guess docs are still incomplete, but just want to let you know of the following issue. When deploying the API following quick start instructions, the confs and other models are not in rapydo module. They are still in the restapi module. However, in the main flask app rapydo is referred. Probably, a packaging issue.

**Comment by pdonorio** [comment]
Hello Harsha, 
we've been working out a new version of Rapydo - with an updated quick start - for the upcoming release candidate, due Monday.

We can check back on this after releasing.

**Comment by pdonorio** [comment]
Hello again,
the `RC1` [has been just released](https://github.com/EUDAT-B2STAGE/http-api/releases/tag/v0.6.0-rc1). You may now try to follow the [new quick start page](https://eudat-b2stage.github.io/http-api/docs/quick_start) and see if your original problem has gone.

At the moment we have no way to directly upgrade one existing release to another, so my suggestion would be to discard all github code and docker images you have before trying the new instructions. This should be fixed in `RC2`.

Note: if you get stuck somewhere please provide as much instructions as possible on how to reproduce the error.

**Comment by Vathasav** [comment]
The problem is solved in RC1 and is working fine. Perhaps, you can add data initialization (restapi init) to the quick start before launching the api.

**Comment by pdonorio** [comment]
> Perhaps, you can add data initialization (restapi init) to the quick start before launching the api

It's already [there](https://github.com/EUDAT-B2STAGE/http-api/blob/0.6.0/docs/quick_start.md#4-deploy-initialization). Is it not clear in that position?

**Comment by pdonorio** [comment]
`restapi init` is executed by the docker image at start. If that is not your case feel free to reopen the issue as that would be a bug. By the way you might have not used the latest docker image build by switching from an older version to RC1. That will be solved with #87.
